# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d068d1228a7334975543c64ae787a6a00de6d0977686a42cf451d91d83a57ccfd9e273d1573f1d33b67b173aa38e90d12ef2f7b5bc8c1cc2b823d4125afbe757

test:
  secret_key_base: 8316aecdb1e8c9809da3115a9c175a9e00b1cad6469df58fdf0895c95977bc68df5680d059512c0ba269a8edf16516d2a39ff4eace8a26fe3a9b2da0d53b7932

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
